[package]
name = "persistence"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
serde = { version = "1.0.210", features = ["derive"] }
thiserror = { workspace = true }
pickledb = "0.5.1"
paris = { workspace = true, optional = true }

[features]
verbose = ["paris"]