// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteWrapper } from "./NoteWrapper";

export type MidiSignal = { airStrength: number, note: NoteWrapper, state: number, };