// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MidiMusic } from "./MidiMusic";

export type MidiMusicList = { files: Array<MidiMusic>, };
