// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * O payload para enviar dados da nota midi para o front
 *
 * [`Self::note_index`] é o index da nota comecando no G3, ou seja, G3 é index 0 e
 * C5 é 15. Esse campo nunca vai ser negativo
 */
export type MidiSignal = { note_index: number, is_bmol: boolean, note_name: string, velocity: number, state: boolean, };
