// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Struct para uma musica, vai possuir o nome, id, e o diretorio dela para localizala rapidamente.
 *
 * Opcionalmente vai ser a sua duração em segundos, esse campo pode ser nulo.
 * Se esse for o caso, chama o comando `music_length`.
 *
 */
export type MidiMusic = { name: string, id: number, directory: string, duration: bigint, };
