// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Note } from "./Note";

/**
 * @deprecated Usa `MidiSignal` agora
 */
export type NoteWrapper = { note: Note, byte: number, };