[package]
name = "midi-output"
version = "0.1.0"
edition = "2021"

[dependencies]
midir = { workspace = true }
serde = { workspace = true, features = ["derive"] }
strum = { workspace = true, features = ["derive"] }
strum_macros = { workspace = true }
paris = { workspace = true, optional = true, features = ["macros"] }
thiserror = { workspace = true }

[features]
verbose = ["paris"]